export const SLICE_COLORS: Array<string> = ["red", "pink", "green", "blue"];

export const WHEEL_SIZE: number = 300;
export const START_VAL = 0;

export const ADJECTIVES: Array<string> = [
    "amiable",
    "artful",
    "altruistic",
    "beguiling",
    "big",
    "bucolic",
    "bumptious",
    "captivating",
    "dapper",
    "dashing",
    "ebullient",
    "ephemeral",
    "facetious",
    "flabbergasted",
    "furtive",
    "gargantuan",
    "gregarious",
    "hapless",
    "iconoclastic",
    "incandescent",
    "impish",
    "jocular",
    "jovial",
    "languid",
    "lissome",
    "luminous",
    "mirthful",
    "nebulous",
    "nefarious",
    "opulent",
    "palpable",
    "pensive",
    "prismatic",
    "quaint",
    "quixotic",
    "rambunctious",
    "resplendent",
    "sagacious",
    "salubrious",
    "sanguine",
    "slippery",
    "taciturn",
    "tenebrous",
    "ubiquitous",
    "unctuous",
    "unreasonable",
    "vexed",
    "vibrant",
    "verbose",
    "wide-eyed",
    "whimsical",
    "winsome",
    "xenial",
    "xenophobic",
    "yawning",
    "yearning",
    "yielding",
    "zealous",
    "zany",
    "zesty"  
];

export const NOUNS: Array<string> = [
    "1920s flapper",
    "motherfucker",
    "musk fanboy",
    "table slapper",
    "twitch streamer"   
]

// https://coolors.co/generate
export const COLORS: Array<string> = [
    '#58BC82',
    '#FC7A57',
    '#8377D1',
    '#6D5A72',
    '#119DA4',
    '#2D3047',
    '#8E3B46',
    '#668F80',
    '#13505B',
    '#73956F',
    '#89023E',
]